/**
 * Auto-generated TypeScript definitions for WhistleZero Compact Smart Contract
 * Generated by Compact Compiler v0.14.0
 */

import type { Contract, WitnessContext } from '@midnight-ntwrk/compact-runtime';

export interface LedgerState {
  total_reports: bigint;
  latest_evidence_commitment: Uint8Array;
  organization_credential_root: Uint8Array;
  active_investigations: bigint;
}

export interface ContractWitnesses {
  whistleblower_credential_secret: (context: WitnessContext) => Promise<Uint8Array>;
  report_content_hash: (context: WitnessContext) => Promise<Uint8Array>;
  department_auth_token: (context: WitnessContext) => Promise<Uint8Array>;
}

export interface WhistleZeroCircuits {
  submit_anonymous_report: (categoryCode: number, urgencyLevel: number) => Promise<{
    categoryCode: number;
    evidenceHash: Uint8Array;
    urgencyLevel: number;
  }>;
  escalate_investigation: () => Promise<void>;
  update_organization_root: (newRoot: Uint8Array) => Promise<void>;
}

export declare class WhistleZeroContract implements Contract<LedgerState, ContractWitnesses, WhistleZeroCircuits> {
  readonly initialLedgerState: LedgerState;
  readonly witnesses: ContractWitnesses;
  readonly circuits: WhistleZeroCircuits;
  constructor(witnesses: ContractWitnesses);
}
